application: inovatyviospratybos
version: 1
runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app


# The URL /index.html is also handled by the Go application.
- url: /index\.html
  script: _go_app
