application: inovatyviospratybos
version: 4
runtime: go
api_version: go1

handlers:

- url: /view/(.*)
  static_files: /view/\1
  upload: /view/.*
  
- url: /
  static_files: index.html
  upload: index.html

- url: /.*
  script: _go_app
